### PR TITLE
Update opengraph images

### PR DESCRIPTION
**Pull request by DilwoarH**
https://trello.com/c/dMAEdrCh/145-update-coronavirus-branding-graphics-on-the-social-cards

### CODE REVIEW

**Comment by vanitabarrett** [comment]
Do we need to update the image in the /coronavirus page header, or is that a separate card?

**Comment by DilwoarH** [comment]
Yh we do - just waiting for the images.

**Comment by vanitabarrett** [comment]
Sounds like the other images still need sign-off but these are good to go, so let's do those other ones as a separate PR 👍

**Comment by DilwoarH** [comment]
Just added support to not show the coronavirus images for the business page

**Pull request merged**
