### PR TITLE
[PROTOTYPE][DO NOT MERGE] Prototype taxon search and attempt to show answer for search

### PR DESCRIPTION
**Pull request by oscarwyatt**
Prototyping of finding the 'answer' to a given search, akin to Google snippets

Head to /browse to try it out

Trello: https://trello.com/c/jdWFR5ZS/161-prototype-assisting-mainstream-browse-search-with-showing-answer

### CODE REVIEW

**Comment by cbaines** [comment]
@oscarwyatt is this still something you're hoping to merge eventually?

**Comment by oscarwyatt** [comment]
@cbaines No it was just a prototype. I've made a copy of this branch so you can close the PR and remove the branch if you'd like 👍

**Comment by cbaines** [comment]
> @cbaines No it was just a prototype. I've made a copy of this branch so you can close the PR and remove the branch if you'd like +1

Great, I'll go ahead and close the Pull Request. Do re-open it in the future if that's useful!

**Comment by benthorner** [comment]
:warning: This application is Continuously Deployed: :warning:

- Merged changes are automatically deployed to staging and production.

- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) **before** you merge.

- Check your branch is being deployed in the [Release app](https://release.publishing.service.gov.uk/applications/collections), after merging.

**Comment by benthorner** [comment]
Removed CD warning.

@oscarwyatt this PR is very old. Do we still need it?

**Pull request closed without merging**
