### PR TITLE
Remove statistics section

### PR DESCRIPTION
**Pull request by leenagupte**
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Trello: https://trello.com/c/gAdJtfsB
Follows on from: https://github.com/alphagov/collections/pull/2727

# What's changed?
Removes all remaining code used to render the statistics section on the coronavirus landing page.

# Why?
On 1st April, the statistics section, NHS box and timeline entries sections were [removed from the the landing page](https://github.com/alphagov/collections/pull/2727). This change removes all of the remaining code used to render the statistics section.

### CODE REVIEW

**Review by gclssvglx — COMMENTED** [review]
Looking good, just a question on a couple of sections...

Do these need removing too?

- https://github.com/alphagov/collections/blob/d4d2ba5b52afc7425818f62a2063b291d0df063e/spec/fixtures/content_store/coronavirus_landing_page.json#L342

- https://github.com/alphagov/collections/blob/d4d2ba5b52afc7425818f62a2063b291d0df063e/spec/fixtures/content_store/coronavirus_landing_page_with_timeline_nations_without_wales.json#L563
- https://github.com/alphagov/collections/blob/7861c940e4f3c33042bb08f1b61101558024847c/spec/features/coronavirus_landing_page_spec.rb#L8
- https://github.com/alphagov/collections/blob/bb488b6e448f9c49f1f56608dc0bf0781329c039/spec/controllers/coronavirus_landing_page_controller_spec.rb#L11
- https://github.com/alphagov/collections/blob/d34f45c7b80985eabf2b3cd30124d12f13a4f12f/spec/support/coronavirus_content_item_helper.rb#L15
- https://github.com/alphagov/collections/blob/d34f45c7b80985eabf2b3cd30124d12f13a4f12f/spec/services/fetch_coronavirus_statistics_service_spec.rb#L6

**Comment by leenagupte** [comment]
> Looking good, just a question on a couple of sections...
> 
> Do these need removing too?
> 
> * https://github.com/alphagov/collections/blob/d4d2ba5b52afc7425818f62a2063b291d0df063e/spec/fixtures/content_store/coronavirus_landing_page.json#L342
> * https://github.com/alphagov/collections/blob/d4d2ba5b52afc7425818f62a2063b291d0df063e/spec/fixtures/content_store/coronavirus_landing_page_with_timeline_nations_without_wales.json#L563
> * https://github.com/alphagov/collections/blob/7861c940e4f3c33042bb08f1b61101558024847c/spec/features/coronavirus_landing_page_spec.rb#L8
> * https://github.com/alphagov/collections/blob/bb488b6e448f9c49f1f56608dc0bf0781329c039/spec/controllers/coronavirus_landing_page_controller_spec.rb#L11
> * https://github.com/alphagov/collections/blob/d34f45c7b80985eabf2b3cd30124d12f13a4f12f/spec/support/coronavirus_content_item_helper.rb#L15
> * https://github.com/alphagov/collections/blob/d34f45c7b80985eabf2b3cd30124d12f13a4f12f/spec/services/fetch_coronavirus_statistics_service_spec.rb#L6

Good spot! Thanks ❤️

**Comment by leenagupte** [comment]
@gclssvglx Thanks for your review. I've removed the test helpers and updated the fixture files now as well. This is ready for a re-review.

**Review by gclssvglx — APPROVED** [review]
Fantastic - thanks @leenagupte 👍

**Pull request merged**
