### PR TITLE
Remove float logic from child taxons grid view

### PR DESCRIPTION
**Pull request by Rosa-Fox**
- Control float logic within css

### CODE REVIEW

**Comment by alextea** [comment]
We will need to test this on browsers. `nth-child` isn't supported in IE8 and lower.

**Comment by alextea** [comment]
We had the same functionality before (@397c29) and removed it because of browser incompatibility issues.

**Comment by alecgibson** [comment]
Here's the original Trello card for context: https://trello.com/c/g8rg70Oa/359-find-a-way-of-making-sure-the-grid-doesn-t-break-without-using-nth-selectors-which-are-not-supported-in-ie8

One day, we'll live in a beautiful, IE-free utopia of `nth` selectors and maybe even `css-grid`. But sadly today is not that day.

Feel free to raise a separate PR to comment on this CSS if you think it would help.

**Comment by Rosa-Fox** [comment]
Thanks both!

**Pull request closed without merging**
