### PR TITLE
[WIP] Increase spacing on news component

### PR DESCRIPTION
**Pull request by huwd**
**To be updated once the a new version of govuk_publishing_components has been released**
This currently uses a branch for some QA checks.

Trello: https://trello.com/c/6bJCf1zv/472-increase-spacing-in-document-list-component

## What

This PR bumps the version of govuk_publishing_components to increase the spacing between elements on a document list.

Specific examples can be found in the news section of the `/transition` page.

## Visual Example
- Right is current version
- Left is new version
Screenshot 2020-02-14 at 13 35 05

### CODE REVIEW

**Comment by huwd** [comment]
Marked this as ready for review so i get a heroku deploy to send to trevor.
Still premature until we get the gem released!

**Comment by huwd** [comment]
👉 heroku...? 
Humm why isn't that app deploying...

**Comment by vanitabarrett** [comment]
@huwd Not sure why it wasn't reporting, but it did actually build a heroku app. I've kicked it off again and it looks like it's appearing here now

**Comment by huwd** [comment]
No need for this now Depbot exists: https://github.com/alphagov/collections/pull/1500

**Pull request closed without merging**
