### PR TITLE
Update cookie serialiser

### PR DESCRIPTION
**Pull request by hannako**
Update cookie serializer from `:marshal` to `:json`. Collections does not read or write any cookies so it's ok to switch to `:json` without transitioning to `:hybrid` first

### CODE REVIEW

**Comment by hannako** [comment]
@barrucadu Is this the right approach for the brakeman errors around cookie serialization? Again. 
(https://github.com/alphagov/specialist-publisher/pull/1471)

**Comment by barrucadu** [comment]
You should also change the cookie serialisation method to `:hybrid`, which will let us switch to `:json` eventually.

**Comment by cbaines** [comment]
> You should also change the cookie serialisation method to `:hybrid`, which will let us switch to `:json` eventually.

Does collections actually set Rails cookies? If it doesn't you could just change the mode to :json, as there's no need to transition cookies.

**Comment by hannako** [comment]
Thanks Chris. I don't think it does set any Rails cookies, or read any either. I'll switch to `:json`

**Pull request merged**
