### PR TITLE
Document collection fixes

### PR DESCRIPTION
**Pull request by carvil**
This PR removes inconsistent entries from the file containing education document collections.

Trello card:
https://trello.com/c/8WkMEUbj/505-document-collections-missing-or-need-amends

### CODE REVIEW

**Comment by alecgibson** [comment]
The Trello link just points to the board, not to the card.

**Comment by carvil** [comment]
@alecgibson bad copy/paste, I've updated the description now

**Comment by alecgibson** [comment]
Even with the Trello card, I'm not sure I understand the context of this card? There's _a lot_ of deletions in this PR - why is that?

**Comment by alecgibson** [comment]
As discussed, please get Holly to product review on integration, and if she's okay with it then it's fine by me.

**Pull request merged**
